#!/bin/bash
cd /tmp/mysql-$3
cmake -DCMAKE_INSTALL_PREFIX=$1 \
  -DMYSQL_DATADIR=$2 \
  -DDEFAULT_CHARSET=utf8 \
  -DDEFAULT_COLLATION=utf8_general_ci \
  -DMYSQL_TCP_PORT=3306 \
  -DMYSQL_UNIX_ADDR=/tmp/mysql.sock \
  -DWITH_MYISAM_STORAGE_ENGINE=1 \
  -DWITH_INNOBASE_STORAGE_ENGINE=1 \
  -DDOWNLOAD_BOOST=1 \
  -DWITH_BOOST=/usr/local/boost \
  -DWITH_INNODB_MEMCACHED=ON
